# Generated by Django 4.2.1 on 2023-10-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_student_notification_student_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_notification',
            name='message',
            field=models.TextField(blank=True, default=True),
        ),
    ]
