# Generated by Django 4.2.1 on 2023-10-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_student_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_notification',
            name='message',
        ),
    ]
