# Generated by Django 4.2.1 on 2023-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_staff_leave_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_leave',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
