# Generated by Django 4.2.1 on 2023-10-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_student_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_notification',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
